#In﻿clude <WinAPI.au3>
#include <Constants.au3>
#include <AutoItConstants.au3>

WinWait("Microsoft account")
WinActivate("Microsoft account")
MouseClick($MOUSE_CLICK_LEFT)
sleep ( 2000 )
Send ("{TAB}")
Sleep ( 200)
Send ("{TAB}")
Sleep ( 200)
Send ("{TAB}")
Sleep ( 200)
Send ("{TAB}")
Sleep ( 200)
Send ("{TAB}")
Sleep ( 200)
Send ("{TAB}")
Sleep ( 200)
Send("{LWIN}")
Sleep( 50)
Send("{LWIN}")
Sleep( 50)
Send("{LWIN}")
Sleep( 50)
Send("{LWIN}")
Sleep( 50)
Send("{LWIN}")